/**
 * Export Service
 * Handles exporting research reports
 */

import { getApiUrl } from "./http";

/**
 * Export conversation as Markdown file
 */
export async function exportAsMarkdown(conversationId: string): Promise<void> {
  const API_URL = getApiUrl();
  const url = `${API_URL}/api/export/${conversationId}/markdown`;

  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Export failed: ${response.statusText}`);
    }

    // Get the blob
    const blob = await response.blob();

    // Create download link
    const downloadUrl = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = downloadUrl;
    link.download = `research_${conversationId}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Clean up
    window.URL.revokeObjectURL(downloadUrl);
  } catch (error) {
    console.error("Export failed:", error);
    throw error;
  }
}

/**
 * Export current research data as Markdown (client-side)
 */
export function exportCurrentAsMarkdown(
  query: string,
  report: string,
  sessionId?: string
): void {
  const markdown = `# Research Report

## Query
${query}

## Session ID
${sessionId || "Current Session"}

## Generated On
${new Date().toLocaleString()}

---

## Report

${report}

---

*Generated by Multi-Agent AI Deep Researcher*
`;

  // Create blob and download
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `research_${sessionId || Date.now()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}
