"use client";

import React, { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { TopNav } from "../../components/TopNav";
import { ResultsSkeleton } from "../../components/Skeleton";
import { getConversation } from "../../services/conversationsService";
import { ConversationDetail } from "../../types/dto";
import "./ShareableReport.css";

const ResearchResults = dynamic(
  () =>
    import("../../components/ResearchResults").then((m) => m.ResearchResults),
  { ssr: false, loading: () => <ResultsSkeleton /> }
);

interface Props {
  id: string;
}

export const ShareableReport: React.FC<Props> = ({ id }) => {
  const [session, setSession] = useState<ConversationDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    setLoading(true);
    setError(null);
    getConversation(id)
      .then((data) => {
        if (active) setSession(data);
      })
      .catch((err) => {
        if (active)
          setError(
            err instanceof Error ? err.message : "Could not load this report."
          );
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [id]);

  const conversation = session?.data?.conversation?.conversation || [];
  const query =
    conversation.find((entry) => entry.type === "query")?.content ?? "";
  const timestamp = session?.timestamp;

  return (
    <div className="share">
      <TopNav variant="landing" />

      <main className="share__main">
        <header className="share__header">
          <div className="share__eyebrow">
            <span className="share__dot" /> Chronicle research report
          </div>
          {query ? (
            <h1 className="share__query">&ldquo;{query}&rdquo;</h1>
          ) : (
            <h1 className="share__query">Research report</h1>
          )}
          <p className="share__meta">
            Report ID <code>{id.slice(0, 12)}</code>
            {timestamp && (
              <>
                {" "}
                &middot; Generated{" "}
                {new Date(timestamp).toLocaleDateString(undefined, {
                  year: "numeric",
                  month: "short",
                  day: "numeric",
                })}
              </>
            )}
          </p>

          <div className="share__cta">
            <Link href="/research" className="share__cta-btn">
              Run your own research &rarr;
            </Link>
            <span className="share__cta-sub">
              Free, open-source, no signup.
            </span>
          </div>
        </header>

        <div className="share__report">
          {loading && <ResultsSkeleton />}
          {error && !loading && (
            <div className="share__error" role="alert">
              <h2>Couldn&rsquo;t load this report.</h2>
              <p>{error}</p>
              <p>
                The link may be invalid, the report may have been deleted, or
                the backend is unreachable.{" "}
                <Link href="/research">Run a new query &rarr;</Link>
              </p>
            </div>
          )}
          {!loading && !error && session && (
            <ResearchResults data={session.data} />
          )}
        </div>

        <footer className="share__footer">
          <div className="share__footer-card">
            <h3>Want one of these for your market?</h3>
            <p>
              Chronicle is an AI research copilot for founders. Customer
              discovery, market sizing, and competitive intel &mdash; with
              citations you can defend.
            </p>
            <Link href="/" className="share__footer-link">
              About Chronicle &rarr;
            </Link>
          </div>
          <p className="share__credit">
            Generated by{" "}
            <Link href="/">Chronicle</Link> &middot; built by{" "}
            <a
              href="https://intelliforge.tech"
              target="_blank"
              rel="noopener noreferrer"
            >
              IntelliForge AI
            </a>
          </p>
        </footer>
      </main>
    </div>
  );
};
