import type { Metadata } from "next";
import { ShareableReport } from "../../../src/views/share/ShareableReport";

interface Props {
  params: { id: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  return {
    title: `Research report \u00b7 ${params.id.slice(0, 8)}`,
    description:
      "Research report generated by Chronicle. Multi-agent AI research with citations and contradiction detection.",
    openGraph: {
      title: "Chronicle research report",
      description:
        "Generated by Chronicle \u2014 AI research copilot for founders.",
      images: ["/og-image.svg"],
    },
  };
}

export default function Page({ params }: Props) {
  return <ShareableReport id={params.id} />;
}
